matrix:
  include:
    - language: java
      jdk:
        - openjdk12
      services:
        - docker
      before_install:
        - chmod +x mvnw
      install: true
      script:
        - ./mvnw install -DskipTests=true
      cache:
        directories:
          - $HOME/.m2
deploy:
  - provider: cloudfoundry
    username: $username
    password: $password
    api: https://api.run.pivotal.io
    organization: ihear
    space: development
