matrix:
  include:
    - language: java
      jdk:
        - openjdk12
      before_install:
        - chmod +x mvnw
      install: true
      script:
        - ./mvnw install -DskipTests=true
      cache:
        directories:
          - $HOME/.m2
          - $TRAVIS_BUILD_DIR/src/main/resources/ui-static/node
      deploy:
        - provider: cloudfoundry
          username: $USERNAME
          password: $PASSWORD
          api: https://api.run.pivotal.io
          organization: ihear
          space: development
